# Generated by Django 5.2.5 on 2025-08-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('moradia', 'Moradia'), ('alimentação', 'Alimentação'), ('transporte', 'Transporte'), ('lazer', 'Lazer'), ('saúde', 'Saúde'), ('investimentos', 'Investimentos'), ('outros', 'Outros')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
