# Generated by Django 5.2.5 on 2025-08-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salario', 'Salario'), ('negócios', 'Negócios'), ('investimento', 'Investmento'), ('outros', 'Outros')], max_length=50),
        ),
    ]
