# Generated by Django 5.2.5 on 2025-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
